---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

# spnethack

The goal of spnethack is to explore spatial networks in R.

# Requirements

We'll use the following packages:

```{r, eval=TRUE, message=FALSE}
library(sf)
library(osmdata)
library(dodgr)
library(stplanr)
library(dplyr)
library(piggyback)
```


# Data

It makes sense to have some input data.

## From josm

Data from OSM was downloaded with the `josm` GUI.
It can be read-in as follows:

```{r}
pb_download("promenade-all.geojson")
promenade_all = read_sf("promenade-all.geojson")
promenade_min = promenade_all %>% 
  filter(name == "Promenade")
# write_sf(promenade_min, "promenade-min.geojson")
```

The minimum dataset can be read-in as follows:

```{r, eval=TRUE}
pb_download("promenade-min.geojson")
promenade_min = read_sf("promenade-min.geojson")
plot(promenade_min$geometry)
```




## From geojson

```{r}
promenade = opq(bbox = "munster") %>% 
  add_osm_feature(key = "name", value = "Promenade")
```

